### ISSUE TITLE
Outdated Informix reference urls

### ISSUE THREAD

**Issue by jbafford** [php/doc-base#88]
The two urls below (both used in `reference/pdo_informix/reference.xml` for https://www.php.net/manual/en/ref.pdo-informix.php and https://www.php.net/manual/en/ref.pdo-informix.connection.php) are both currently redirecting to https://www.ibm.com/support/pages/publications-ibm-informix-dynamic-server-10-family-products. Someone who is more familiar with Informix should figure out updated links for the intended content.

```
<!ENTITY url.informix.connectionstring "http://publib.boulder.ibm.com/infocenter/idshelp/v10/topic/com.ibm.odbc.doc/odbc66.htm#sii02998361">
<!ENTITY url.informix.dsn "http://publib.boulder.ibm.com/infocenter/idshelp/v10/index.jsp">
```

**Comment by cmb69** [comment]
> Someone who is more familiar with Informix should figure out updated links for the intended content.

Yeah, that is likely a problem.

**Comment by cmb69** [comment]
The link in the [description of the PECL package](https://pecl.php.net/package/PDO_INFORMIX) is also out-dated.
